// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using System.Runtime.InteropServices;

public  abstract class Bonjour_Type_Base
{
	public Bonjour_Type_Base ()
	{
	}

	public abstract void initSDK();

	public abstract void ShowLogin();
    public abstract void ShowLogin(string loginType);
	public abstract void ShowLogout();
	public abstract void ShowPersonCenter();
	public abstract void HidePersonCenter();
	public abstract void ShowToolBar();
	public abstract void HideToolBar();
	public abstract string PayItem(U3DTypeBaseData _in_pay);
	public abstract int LoginState();
	public abstract void ShowShare(U3DTypeBaseData _in_share);
	public abstract void SetPlayerInfo(U3DTypeBaseData data);
	public abstract U3DTypeBaseData GetUserData();
	public abstract U3DTypeBaseData GetPlatformData();
	//
	public abstract void CopyClipboard(U3DTypeBaseData data);
	public abstract bool IsHasRequest(string requestType);
	public abstract void Destory();
	public abstract void ExitGame();

	/**call any undefine function if success or return error*/
	public abstract string DoAnyFunction(string funcName,U3DTypeBaseData _in_data);
	/**get phone info */
	public abstract string DoPhoneInfo();

	public abstract void AddLocalPush(U3DTypeBaseData _push_data);

	public abstract void RemoveLocalPush(string pushid);

    public abstract void RemoveAllLocalPush();

	public abstract void GetUserFriends();
}


