// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using System.Runtime.InteropServices;

#if UNITY_IOS

public class Bonjour_Type_Common_IOS:Bonjour_Type_Base
{
	[DllImport("__Internal")]
	private static extern void CallInitSDK();
	[DllImport("__Internal")]
	private static extern void CallShowLogin ();
	[DllImport("__Internal")]
	private static extern void CallShowLogout ();
	[DllImport("__Internal")]
	private static extern void CallShowPersonCenter ();
	[DllImport("__Internal")]
	private static extern void CallHidePersonCenter ();
	[DllImport("__Internal")]
	private static extern void CallShowToolBar ();
	[DllImport("__Internal")]
	private static extern void CallHideToolBar ();
	[DllImport("__Internal")]
	private static extern string CallPayItem (string _json_string);
	[DllImport("__Internal")]
	private static extern int CallLoginState ();
	[DllImport("__Internal")]
	private static extern void CallShowShare (string _json_string);
	[DllImport("__Internal")]
	private static extern void CallSetPlayerInfo (string _json_string);
	[DllImport("__Internal")]
	private static extern string CallGetUserData ();
	[DllImport("__Internal")]
	private static extern string CallGetPlatformData ();
	[DllImport("__Internal")]
	private static extern void CallCopyClipboard (string _json_string);
	[DllImport("__Internal")]
	private static extern bool CallIsHasRequest (string _json_string);
	[DllImport("__Internal")]
	private static extern void CallDestory ();
	[DllImport("__Internal")]
	private static extern void CallExitGame ();
	[DllImport("__Internal")]
	private static extern string CallDoAnyFunction (string _funcName_string,string _json_string);
	[DllImport("__Internal")]
	private static extern string CallPhoneInfo ();
	[DllImport("__Internal")]
	private static extern void CallAddLocalPush(string _json_data);
	[DllImport("__Internal")]
	private static extern void CallRemoveLocalPush(string _json_data);
	[DllImport("__Internal")]
	private static extern void CallRemoveAllLocalPush();
	[DllImport("__Internal")]
	private static extern void CallGetUserFriends();


	public override void initSDK()
	{
		CallInitSDK();
	}
	public override void ShowLogin()
	{
		CallShowLogin();
	}
    public override void ShowLogin(string loginType)
	{
		CallShowLogin();
	}
	public override void ShowLogout()
	{
		CallShowLogout();
	}
	public override void ShowPersonCenter()
	{
		CallShowPersonCenter();
	}
	public override void HidePersonCenter()
	{
		CallHidePersonCenter();
	}
	public override void ShowToolBar()
	{
		CallShowToolBar();
	}
	public override void HideToolBar()
	{
		CallHideToolBar();
	}
	public override string PayItem(U3DTypeBaseData _in_pay)
	{
		string billNo ="";
		billNo= CallPayItem(_in_pay.DataToString());
		return billNo;
	}
	public override int LoginState()
	{
		int state = 0;
		state = CallLoginState();
		return state;
	}
	public override void ShowShare(U3DTypeBaseData _in_share)
	{
		CallShowShare(_in_share.DataToString());
	}
	public override void SetPlayerInfo(U3DTypeBaseData data)
	{
		CallSetPlayerInfo(data.DataToString());
	}
	public override U3DTypeBaseData GetUserData()
	{
		string value = CallGetUserData();

		U3DTypeBaseData outData = new U3DTypeBaseData();
		outData.StringToData(value);
		return outData;

	}
	public override U3DTypeBaseData GetPlatformData()
	{
		string value = CallGetPlatformData();
		
		U3DTypeBaseData outData = new U3DTypeBaseData();
		outData.StringToData(value);
		return outData;
	}
	//
	public override void CopyClipboard(U3DTypeBaseData data)
	{
		CallCopyClipboard(data.DataToString());
	}
	public override bool IsHasRequest(string requestType)
	{
		bool result = false;
		result =  CallIsHasRequest(requestType);
		return result;
	}
	public override void Destory()
	{
		CallDestory();
	}
	public override void ExitGame()
	{
		CallExitGame();
	}
	
	/**call any undefine function if success or return error*/
	public override string DoAnyFunction(string funcName,U3DTypeBaseData _in_data)
	{
		string result = "";
		result = CallDoAnyFunction(funcName,_in_data.DataToString());
		return result;
	}

	public override string DoPhoneInfo()
	{

		string value = CallPhoneInfo();
		return value;
	}

	//1.增加一个本地推送
	public override void AddLocalPush(U3DTypeBaseData data)
    {
        Debug.Log("AddLocalPush : "+ data.DataToString());
		CallAddLocalPush (data.DataToString());
    }		
			
	//2解除一个本地推送
	public override void RemoveLocalPush(string	_push_id)
	{
		Debug.Log("RemoveLocalPush : "+ _push_id);
		CallRemoveLocalPush (_push_id);
	}
			
	//3解除所有本地推送
	public override void RemoveAllLocalPush()
	{
		CallRemoveAllLocalPush ();
	}
	public override void GetUserFriends ()
	{
		CallGetUserFriends ();
	}
}
#endif
