// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections;
using UnityEngine;
using System.Collections.Generic;

	public class GameStaticConfig
	{
		public static int att_fontsize;
		public static  Rect[] arr_LOCATION ;

		public GameStaticConfig ()
		{
		}
		public static void modifyArrlocation()
		{
			
			float btnW = Screen.width / 3;
			float btnH = Screen.height / 8;
			
			
			if (btnH > btnW / 3)
				btnH = btnW / 3;
			
			float startX = Screen.width /2 -Screen.width/6;
			float startY = Screen.height / 60;
			arr_LOCATION = new Rect[11] ;
			
			for (int i = 0; i<6; ++i) 
			{
				arr_LOCATION[i].x =  startX;
				arr_LOCATION[i].y = btnH + (startY + btnH)*i;
				arr_LOCATION[i].width = btnW;
				arr_LOCATION[i].height = btnH;
			}
//			arr_LOCATION[INDEX_MESSAGE_LOCATION].width = btnW * 3;
//			arr_LOCATION[INDEX_MESSAGE_LOCATION].x = 0;
			
			att_fontsize = (int)(btnH * 0.8);
		}
	}


