// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using TypeSDKTool;
using TypeDataModel;
using System.Collections.Generic;


public class LoginScene:MonoBehaviour
{
	public LoginScene ()
	{
	}
	void Start()
	{
		//设置屏幕自动旋转， 并置支持的方向
		
		Screen . orientation = ScreenOrientation . AutoRotation ;
		
		Screen . autorotateToLandscapeLeft = true ;
		
		Screen . autorotateToLandscapeRight = true ;
		
		Screen . autorotateToPortrait = false ;
		
		Screen . autorotateToPortraitUpsideDown = false ;

//		U3DTypeSDK.Instance.AddEventDelegate(TypeEventType.EVENT_LOGIN_SUCCESS, LoginResult);

	}

	void OnGUI()
	{
		GameStaticConfig.modifyArrlocation ();
		GUI.skin.button.fontSize = GameStaticConfig.att_fontsize;
		//调用登录
		if (GUI.Button(GameStaticConfig.arr_LOCATION[2], "登录"))
		{
			U3DTypeSDK.Instance.RemoveEventDelegate(TypeEventType.EVENT_LOGIN_SUCCESS);
//			U3DTypeSDK.Instance.AddEventDelegate(TypeEventType.EVENT_LOGIN_SUCCESS,LoginResult);
			
			U3DTypeSDK.Instance.Login();
		}
	}

//	void LoginResult(U3DTypeEvent evt)
//	{
//		Debug.Log("LoginResult");
//		
//		U3DTypeBaseData data = evt.evtData;
//		
//		
//		//string userName = data.GetData(U3DTypeAttName.USER_NAME);
//		string userID = data.GetData(U3DTypeAttName.USER_ID);
//		string userToken = data.GetData(U3DTypeAttName.USER_TOKEN);
//		
//		//		Dictionary<string,string> dataArr = new Dictionary<string,string> ();
//		
//		U3DTypeBaseData platform = U3DTypeSDK.Instance.GetPlatformData();
//		
//		U3DTypeBaseData baseData = new U3DTypeBaseData ();
//		baseData.SetData ("id", userID);
//		baseData.SetData ("token", userToken);
//		baseData.SetData ("data", "");
//		baseData.SetData("cid",platform.GetData(U3DTypeAttName.CHANNEL_ID));
//		baseData.SetData ("sign", userID + "|" + userToken + "|" + ""+"|"+platform.GetData(U3DTypeAttName.CHANNEL_ID));
//		
//		string dataArr = changeBaseDataToHttpData (baseData);
//		Debug.Log ("login sent to server data " + dataArr);
//		DataProxy.Ins.ServerLogic.RequestLogin (this,dataArr, ServerCBK_login, null);
//		//send user info to server and exchange playerinfo;
//	}
}


