//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Text;
namespace TypeSDKTool
{
	public class StringTool
	{
		public StringTool ()
		{
		}
		public static string UrlEncode(string str)
		{

			StringBuilder sb = new StringBuilder();
			byte[] byStr = System.Text.Encoding.UTF8.GetBytes(str); //默认是System.Text.Encoding.Default.GetBytes(str)
			for (int i = 0; i < byStr.Length; i++)
			{
				sb.Append(@"%" + Convert.ToString(byStr[i], 16));
			}
			
			return (sb.ToString());
		}

		public static string MD5StringByString(string _in_string)
		{
			System.Security.Cryptography.MD5 md5 = System.Security.Cryptography.MD5.Create(); 
			byte[] inputBytes = System.Text.Encoding.ASCII.GetBytes(_in_string); 
			byte[] hash = md5.ComputeHash(inputBytes); 
			StringBuilder sb = new StringBuilder(); 
			for (int i = 0; i < hash.Length; i++) 
			{ 
				sb.Append(hash[i].ToString("X2")); 
			} 
			return sb.ToString(); 
		}


	}

}

